### ISSUE TITLE
Funzione displayCondition non viene chiamata durante la creazione del widget

### ISSUE THREAD

**Issue by LeoRc01** [fradesa/FlutterBoringForm#13]
Caso d'uso:
Ho una checkBox che se checkata mi mostra un formField, se non è checkata non viene mostrato.
Di base, la checkBox non è checkata quindi valore false, però il formField viene comunque mostrato. 
Avviene il trigger della funzione displayCondition solamente quando vado a cambiare valore alla checkBox

**Comment by LeoRc01** [comment]
Una soluzione potrebbe essere un parametro "initiallyDispayed" o una roba simile. Oppure triggerare la funzione di display dopo la creazione del widget

**Comment by fradesa** [comment]
Potrebbe essere che non prende l'initial value corretto?
Perchè mi pare che con altri field funzioni correttamente (es: se la data è minore di un certo giorno allora mostra il boringField)

**Comment by LeoRc01** [comment]
in effetti ho visto ora provando a dargli un initialValue dal controller e non funziona. Pero' se lo do ad un textfield normale funziona
